name: "New Jumpstart"
description: "Propose a new Fabric Jumpstart package"
title: "[Jumpstart]: "
labels: ["Jumpstart", "Needs-Triage"]
projects: ["microsoft/2147"]
body:
  - type: markdown
    attributes:
      value: "Please provide enough detail to scope, build, and review this jumpstart."
  - type: input
    id: title
    attributes:
      label: Jumpstart title
      description: Short, user-facing name
      placeholder: "Contoso Real-Time Analytics"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One- or two-sentence overview of the jumpstart
      placeholder: "Accelerates ingestion, streaming, and dashboarding for logistics events."
    validations:
      required: true
  - type: dropdown
    id: solution_type
    attributes:
      label: Solution type
      description: Select the jumpstart category
      options:
        - tutorial
        - accelerator
        - demo
    validations:
      required: true
  - type: checkboxes
    id: workloads
    attributes:
      label: Workloads involved
      description: Select all applicable workloads
      options:
        - label: Data Engineering
        - label: Data Warehouse
        - label: Data Science
        - label: Real Time Intelligence
        - label: Data Factory
        - label: SQL Database
        - label: Power BI
        - label: Other (describe below)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Detailed description
      description: What this jumpstart does; key features and benefits
      placeholder: "This jumpstart enables users to..."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why this jumpstart is needed; target persona and scenario
      placeholder: "This jumpstart helps data engineers learn how to..."
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Target audience
      description: Who this jumpstart is intended for? This should delineate if the Jumpstart is broadly applicable or targeted to a specific scenario, event, etc.
      placeholder: "This jumpstart is designed for data engineers..."
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Fabric items, libraries, data sources, external services
      placeholder: "- Requires Workspace features X\n- Depends on library Y>=1.2\n- Needs demo storage account"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct and Licensing
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Azure/fabric-jumpstart/blob/main/CODE_OF_CONDUCT.md) and the project's [MIT license](https://github.com/microsoft/fabric-jumpstart/blob/main/LICENSE-CODE).
      options:
        - label: I agree to follow this project's Code of Conduct and Licensing terms.
          required: true