/**
 * GitHub REST API helper for submitting a new jumpstart as a pull request.
 *
 * Uses the contributor's own GitHub PAT (obtained via githubAuth.ts) with
 * `public_repo` scope.  All calls are client-side fetch to api.github.com —
 * no server required.  The token is never sent anywhere except GitHub's API.
 */

const UPSTREAM_OWNER = 'microsoft';
const UPSTREAM_REPO = 'fabric-jumpstart';
const BASE_BRANCH = 'main';

export type SubmitStep =
  | 'connect'
  | 'fork'
  | 'branch'
  | 'yaml'
  | 'svgLight'
  | 'svgDark'
  | 'pr';

export type StepStatus = 'pending' | 'running' | 'done' | 'error';

export type ProgressCallback = (step: SubmitStep, status: StepStatus, detail?: string) => void;

export interface SubmitResult {
  prUrl: string;
  prNumber: number;
}

function toBase64(content: string): string {
  const bytes = new TextEncoder().encode(content);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

async function ghFetch(
  token: string,
  path: string,
  options: RequestInit = {}
): Promise<Response> {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(options.headers ?? {}),
    },
  });
  return res;
}

async function ghJson<T>(token: string, path: string, options: RequestInit = {}): Promise<T> {
  const res = await ghFetch(token, path, options);
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API error ${res.status} on ${path}: ${body}`);
  }
  return res.json() as Promise<T>;
}

async function getAuthenticatedUser(token: string): Promise<string> {
  const data = await ghJson<{ login: string }>(token, '/user');
  return data.login;
}

async function forkRepo(token: string, owner: string): Promise<void> {
  await ghFetch(token, `/repos/${UPSTREAM_OWNER}/${UPSTREAM_REPO}/forks`, {
    method: 'POST',
    body: JSON.stringify({ organization: undefined }),
  });

  // Poll until the fork appears (GitHub creates forks asynchronously)
  const deadline = Date.now() + 45_000;
  while (Date.now() < deadline) {
    try {
      const res = await ghFetch(token, `/repos/${owner}/${UPSTREAM_REPO}`);
      if (res.ok) return;
    } catch {
      // not ready yet
    }
    await new Promise((r) => setTimeout(r, 2000));
  }
  throw new Error('Fork creation timed out after 45 seconds.');
}

async function getMainSha(token: string, owner: string): Promise<string> {
  const data = await ghJson<{ object: { sha: string } }>(
    token,
    `/repos/${owner}/${UPSTREAM_REPO}/git/ref/heads/${BASE_BRANCH}`
  );
  return data.object.sha;
}

async function createBranch(token: string, owner: string, branch: string, sha: string): Promise<void> {
  await ghJson(token, `/repos/${owner}/${UPSTREAM_REPO}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha }),
  });
}

async function commitFile(
  token: string,
  owner: string,
  branch: string,
  filePath: string,
  content: string,
  message: string
): Promise<void> {
  await ghJson(token, `/repos/${owner}/${UPSTREAM_REPO}/contents/${filePath}`, {
    method: 'PUT',
    body: JSON.stringify({
      message,
      content: toBase64(content),
      branch,
    }),
  });
}

async function createPullRequest(
  token: string,
  forkOwner: string,
  branch: string,
  title: string,
  body: string
): Promise<{ html_url: string; number: number }> {
  return ghJson<{ html_url: string; number: number }>(
    token,
    `/repos/${UPSTREAM_OWNER}/${UPSTREAM_REPO}/pulls`,
    {
      method: 'POST',
      body: JSON.stringify({
        title,
        body,
        head: `${forkOwner}:${branch}`,
        base: BASE_BRANCH,
      }),
    }
  );
}

function buildPrBody(name: string, logicalId: string, description: string): string {
  return `## New Jumpstart: ${name}

This pull request was generated by the [Fabric Jumpstart creation tool](https://fabricjumpstart.microsoft.com/catalog/create/).

| Field | Value |
|---|---|
| **Logical ID** | \`${logicalId}\` |
| **Description** | ${description} |

### Included files
- \`src/fabric_jumpstart/fabric_jumpstart/jumpstarts/community/${logicalId}.yml\`
- \`assets/images/diagrams/${logicalId}_light.svg\`
- \`assets/images/diagrams/${logicalId}_dark.svg\`

---

> [!NOTE]
> Thank you for contributing a jumpstart! The \`id\` field in the manifest will be assigned by maintainers at review time.

# Why this change is needed

New community jumpstart contribution: **${name}**.

# How

Jumpstart manifest, light and dark architecture diagram SVGs committed to the community directory.

# Test

- Tested locally using \`js._install_from_github(...)\` before submission.

# Closes issue

<!-- Link related issue if applicable -->
`;
}

export async function submitJumpstartPr(
  logicalId: string,
  name: string,
  description: string,
  yamlContent: string,
  svgLight: string,
  svgDark: string,
  onProgress: ProgressCallback
): Promise<SubmitResult> {
  const branch = `add-jumpstart/${logicalId}`;

  // Step 1: Connect & resolve user
  onProgress('connect', 'running');
  let forkOwner: string;
  try {
    forkOwner = await getAuthenticatedUser();
    onProgress('connect', 'done', forkOwner);
  } catch (e) {
    onProgress('connect', 'error', String(e));
    throw e;
  }

  // Step 2: Fork
  onProgress('fork', 'running');
  try {
    await forkRepo(forkOwner);
    onProgress('fork', 'done');
  } catch (e) {
    onProgress('fork', 'error', String(e));
    throw e;
  }

  // Step 3: Create branch
  onProgress('branch', 'running');
  try {
    const sha = await getMainSha(forkOwner);
    await createBranch(forkOwner, branch, sha);
    onProgress('branch', 'done');
  } catch (e) {
    onProgress('branch', 'error', String(e));
    throw e;
  }

  // Step 4: Commit YAML
  onProgress('yaml', 'running');
  try {
    const yamlPath = `src/fabric_jumpstart/fabric_jumpstart/jumpstarts/community/${logicalId}.yml`;
    await commitFile(forkOwner, branch, yamlPath, yamlContent, `feat: add ${logicalId} jumpstart manifest`);
    onProgress('yaml', 'done');
  } catch (e) {
    onProgress('yaml', 'error', String(e));
    throw e;
  }

  // Step 5: Commit light SVG
  onProgress('svgLight', 'running');
  try {
    const lightPath = `assets/images/diagrams/${logicalId}_light.svg`;
    await commitFile(forkOwner, branch, lightPath, svgLight, `feat: add ${logicalId} light diagram`);
    onProgress('svgLight', 'done');
  } catch (e) {
    onProgress('svgLight', 'error', String(e));
    throw e;
  }

  // Step 6: Commit dark SVG
  onProgress('svgDark', 'running');
  try {
    const darkPath = `assets/images/diagrams/${logicalId}_dark.svg`;
    await commitFile(forkOwner, branch, darkPath, svgDark, `feat: add ${logicalId} dark diagram`);
    onProgress('svgDark', 'done');
  } catch (e) {
    onProgress('svgDark', 'error', String(e));
    throw e;
  }

  // Step 7: Open PR
  onProgress('pr', 'running');
  try {
    const prTitle = `feat: Add ${name} jumpstart`;
    const prBody = buildPrBody(name, logicalId, description);
    const pr = await createPullRequest(forkOwner, branch, prTitle, prBody);
    onProgress('pr', 'done', pr.html_url);
    return { prUrl: pr.html_url, prNumber: pr.number };
  } catch (e) {
    onProgress('pr', 'error', String(e));
    throw e;
  }
}
