export const ACTION = {
  SET_MENU: 'SET_MENU',
  SET_MENU_ITEMS: 'SET_MENU_ITEMS',
  SET_MENU_DATA: 'SET_MENU_DATA',
  SET_ACTIVE_PATH: 'SET_ACTIVE_PATH',
  SET_IS_MENU_OPEN: 'SET_IS_MENU_OPEN',
  SET_JUMP_TO_SECTION_LIST: 'SET_JUMP_TO_SECTION_LIST',
  SET_DROPS_FILTER: 'SET_DROPS_FILTER',
  RESET_DROPS_FILTER: 'RESET_DROPS_FILTER',
  SET_DROPS_SHORTING_TYPE: 'SET_DROPS_SHORTING_TYPE',
  SET_IS_DROP_FILTER_OPEN: 'SET_IS_DROP_FILTER_OPEN',
  SET_DROPS_VIEW_AND_DOWNLOAD_DATA: 'SET_DROPS_VIEW_AND_DOWNLOAD_DATA',
};
